#################### Posts Api ####################
###
GET http://localhost:3000

###
GET http://localhost:3000/posts

###
GET http://localhost:3000/posts?sender=Gal

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "sender" : "Gabi",
    "title" : "My First Post",
    "content" : "Hello World, This is My First Post"
}

###
PUT http://localhost:3000/posts/1
Content-Type: application/json

{
    "content" : "Hello World, This is My Updated Post"
}

###
DELETE  http://localhost:3000/posts/2

#################### Comments Api ####################

###
GET http://localhost:3000/posts