###
GET http://localhost:3000

######################################################
#################### Posts Api #######################
######################################################

###
GET http://localhost:3000/posts

###
GET http://localhost:3000/posts?sender=Gal

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "sender" : "Gabi",
    "title" : "My First Post",
    "content" : "Hello World, This is My First Post"
}

###
PUT http://localhost:3000/posts/1
Content-Type: application/json

{
    "content" : "Hello World, This is My Updated Post"
}

###
DELETE  http://localhost:3000/posts/1

######################################################
#################### Comments Api ####################
######################################################

###
GET http://localhost:3000/comments

###
POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId" : 3,
    "sender" : "Gabi",
    "content" : "Some comment"
}

###
PUT http://localhost:3000/comments/2
Content-Type: application/json

{
    "content" : "Some other comment"
}

###
DELETE  http://localhost:3000/comments/1

###
GET http://localhost:3000/comments/3